// Build script: embeds every `../checksums/<tag>.sha256sums` file as a
// compile-time `&[(tag, contents)]` slice, accessible from src as
// `include!(concat!(env!("OUT_DIR"), "/embedded_checksums.rs"))`.
//
// Rebuild triggers:
//   * any file under `../checksums/` changes
//   * this build.rs changes (implicit)

use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let checksums_dir = manifest_dir.join("..").join("checksums");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", checksums_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    if checksums_dir.is_dir() {
        for entry in fs::read_dir(&checksums_dir).expect("reading checksums dir") {
            let entry = entry.expect("checksums entry");
            let path = entry.path();
            let Some(stem) = extract_tag(&path) else {
                continue;
            };
            // Tell cargo to rerun if this specific file changes. Needed in
            // addition to the dir watch so edits to individual files trigger a
            // rebuild even if the filesystem doesn't update the dir mtime.
            println!("cargo:rerun-if-changed={}", path.display());
            let contents = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
            entries.push((stem, contents));
        }
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from("// @generated by build.rs — do not edit.\n");
    out.push_str("pub const EMBEDDED_CHECKSUMS: &[(&str, &str)] = &[\n");
    for (tag, contents) in &entries {
        writeln!(out, "    ({tag:?}, {contents:?}),").expect("write to String never fails");
    }
    out.push_str("];\n");

    let out_path = out_dir.join("embedded_checksums.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("writing {}: {e}", out_path.display()));
}

fn extract_tag(path: &Path) -> Option<String> {
    let name = path.file_name()?.to_str()?;
    let tag = name.strip_suffix(".sha256sums")?;
    if tag.is_empty() {
        return None;
    }
    Some(tag.to_owned())
}
